# Generated by Django 2.2.9 on 2020-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
